- bot.py
- cogs/claim.py
- cogs/help.py
- cogs/mickie.py
- cogs/modals/feedback.py
- cogs/report.py
- cogs/views/lead.py
- cogs/views/tech.py
- main.py
I added docstrings and typehints to most of the functions.
> Added documentation

- README.md
- bot.py
- cogs/case.py
- cogs/claim.py
- cogs/help.py
- cogs/mickie.py
- cogs/modals/feedback.py
- cogs/report.py
- cogs/views/lead.py
- cogs/views/tech.py
- main.py
In this branch, I created a Claim class (as defined in case.py) which creates an object representation of a case claim. This is so then we can store all of the information about a case claim in a central location. For the future, this will make logging cases easier, and it'll make looking up which cases are being actively worked on much easier.
In the future, this can be used to assign modals and views to case claims, which will then allow the bot to be able to survive restarts.
> Claim class

- cogs/report.py
- main.py
Fixed /report command
Fixed creation of config.json when running the bot in main.py
> Report hotfix

- bot.py
- cogs/claim.py
- cogs/flag.py
- cogs/report.py
Added the /flag command to allow leads to manually flag cases.
> Flag command

- cogs/claim.py
- cogs/report.py
Polished up the internals of the report command and added a _flagged_ parameter. Also polished up the internals of the _claim_ command and added a check to make sure claims can only be sent in the claims channel.
> Polish report and claim commands

- README.md
- bot/bot.py
- bot/claim.py
- bot/cogs/case_info_command.py
- bot/cogs/help_command.py
- bot/cogs/ping_command.py
- bot/cogs/report_command.py
- bot/modals/feedback_modal.py
- bot/views/lead_view.py
Changed the wording of flag to ping according to Sam's recommendation. No new functionality was added.
As a side note, before the bot is deployed log.csv will need to be cleared.
> Renamed flag to ping

- bot/cogs/case_info_command.py
Made a quick hotfix for /case_info
> Made /case_info show an ephemeral message

- README.md
- bot/bot.py
- bot/cogs/case_info_command.py
- bot/cogs/help_command.py
- bot/cogs/leaderboard_command.py
- bot/cogs/mycases_command.py
- bot/paginator.py
Added /mycases and /leaderboard commands. Made some improvements to /caseinfo as well. Code has been tested and is good to go for deployment.
> New Commands

- bot/cogs/report_command.py
Fixed formatting of /report as per Sam's request.
> Fixed formatted of /report

- README.md
- bot/bot.py
- bot/cogs/caseinfo_command.py
- bot/cogs/claim_command.py
- bot/cogs/getlog_command.py
- bot/cogs/help_command.py
- bot/cogs/leaderboard_command.py
- bot/cogs/mickie_command.py
- bot/cogs/mycases_command.py
- bot/cogs/ping_command.py
- bot/cogs/report_command.py
- bot/cogs/update_percent_command.py
- bot/modals/feedback_modal.py
- bot/views/lead_view.py
- bot/views/leaderboard_view.py
- bot/views/resolve_ping_view.py
- main.py
This branch is ready to be tested on the beta bot to ensure that it works on the computer at the helpdesk.
**Change log**
- Added `/getlog` for leads (mainly for developer use) in order to access the logfile
- Added support for an error channel where all errors relating to commands are sent
- Added a bug fix to /caseinfo
- Added a bug fix to the My Rank button for users who don't have a profile picture
- Added a bug fix for case submission time when a lead checks a case
- Added ping severity and comment filtering so that whitespace and \n aren't included
**FOR DEPLOYMENT**
The bot is running on this branch right now (a hotfix was implemented that needed to be deployed ASAP).
To update the main bot, please do the following:
1. `git checkout main`
2. `git pull`
3. Add the error channel ID …
> Fixes and Logging

- bot/cogs/report_command.py
- bot/helpers.py
Hotfix for errors with the /ping and /report command. I determined the issue was because I tried to find the case information by looking in the log file instead of looking in the active_cases.json file.
I also fixed an error with /report where sorting by month didn't work.
> Ping hotfix

- bot/views/leaderboard_view.py
Fixed a bug where if a user didn't have any cases claimed for the month/semester a ValueError would be raised.
> Fixed MyRank feature

- bot/bot.py
- bot/cogs/getlog_command.py
- bot/modals/feedback_modal.py
- bot/views/lead_view_red.py
- bot/views/resolve_ping_view.py
Made it so when the Ping button is pressed, the checker message is still visible except buttons are grayed out (used for if a lead accidentally clicks out of the modal).
Added the unping button to mark a case as Checked in the log file.
> Pingview update

- bot/bot.py
A few views aren't persistent so I added them.
> Added quick view persistence fix

- bot/bot.py
Added a new looping task that pings the database every 30 minutes to prevent it from disconnecting.
> Added disconnection fix

- bot/views/check_view_red.py
Simple fix for a Kudos form appearing instead of a Ping form
> Fixed ping issue

- .gitignore
- README.md
- bot/bot.py
- bot/cogs/export_command.py
- bot/forms/join_form.py
- bot/models/active_claim.py
- bot/models/announcement.py
- bot/models/checked_claim.py
- bot/models/completed_claim.py
- bot/models/database_item.py
- bot/models/outage.py
- bot/models/ping.py
- bot/models/user.py
- bot/views/check_view.py
- bot/views/check_view_red.py
- bot/views/kudos_view.py
- bot/views/outage_view.py
- sql/cleardb.sql
- sql/import_from_csv.py
Added more documentation, added the /export command to allow a lead to backup the MySQL database tables.
Also added a Python script inside the SQL folders that allows a user to submit a CSV backups into the MySQL database.
> SQL Export

- bot/cogs/report_command.py
- bot/models/checked_claim.py
- bot/status.py
Added the option to specify a specific status type when generating a report as well as added a message containing the report parameters
This PR isn't urgent and I'll probably deploy it sometime next week when I'm in the office.
> Report enhancements

- bot/bot.py
- bot/cogs/leaderboard_command.py
- bot/views/leaderboard_view.py
The leaderboard no longer has the icon on the right side and a few stylistic changes have been made.
> Leaderboard updates

- bot/bot.py
- bot/cogs/help_command.py
- bot/cogs/ping_command.py
- bot/forms/ping_form.py
- bot/models/checked_claim.py
Re-added the /ping command. This implementation allows a lead to manually ping any CheckedClaim that isn't already marked as Pinged.
> Ping command

- README.md
- bot/bot.py
- bot/cogs/report_command.py
- bot/forms/affirm_form.py
- bot/forms/join_form.py
- bot/models/user.py
- bot/views/resolve_ping_view.py
Before deploying, add **log_channel** to `config.json`
Run the following command in MySQL: ```ALTER TABLE Users DROP COLUMN `active`;```
**Changelog:**
Fixed #55 (Removed affirm button)
Fixed #54 (Wrapped remove statements in try-except)
Fixed #31 (Added restrictions to /report command)
Fixed #56 (Removed active columns from Users table)
> Various changes

- bot/bot.py
- bot/cogs/announcement_command.py
- bot/cogs/award_command.py
- bot/cogs/casedist_command.py
- bot/cogs/claim_command.py
- bot/cogs/export_command.py
- bot/cogs/getlog_command.py
- bot/cogs/leaderboard_command.py
- bot/cogs/leadstats_command.py
- bot/cogs/ping_command.py
- bot/cogs/report_command.py
- bot/forms/announcement_form.py
- bot/forms/join_form.py
- bot/models/team.py
- bot/models/user.py
- bot/views/affirm_view.py
- bot/views/leaderboard_view.py
- bot/views/resolve_ping_view.py
- sql/cleardb.sql
- sql/createdb.sql
- sql/viewdb.sql
Changes to MySQL database:
```sql
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `Teams`(
`role_id` BIGINT UNSIGNED NOT NULL,
`color` VARCHAR(7) NOT NULL,
`image_url` MEDIUMTEXT NOT NULL,
`points` BIGINT NOT NULL
);
ALTER TABLE `Teams` ADD PRIMARY KEY(`role_id`);
ALTER TABLE `Users` ADD CONSTRAINT `users_team_foreign` FOREIGN KEY(`team`) REFERENCES `Teams`(`role_id`);
INSERT INTO Teams (role_id, color, image_url, points) VALUES
(),
(),
(),
(),
(0, '', '', 0);
```
Side note: PAs with the team assignment **White Lotus** will need their `team` column in the Users table to be set to 0.
Changelog:
- Fixed #60 
- Fixed #41 
- Fixed #61 
- Fixed #49
> Fixing issues

- bot/models/checked_claim.py
- bot/views/leaderboard_view.py
Changelog:
- Fixed #62 (Added `12341234` as a blacklisted case number)
- Fixed #64
> Minor adjustments

- bot/bot.py
- bot/models/team.py
- bot/views/leaderboard_view.py
Changelog:
- /award command no longer replaces team total
- The server icon is updated everytime the Refresh button is pressed
> Award hotfix

- bot/forms/ping_form.py
> New minor fixes

- .gitignore
- backup_generator.py
- bot/cogs/help_command.py
- bot/views/leaderboard_view.py
Fixed some very minor issues, and trying a few new things.
> Fixed #70, Fixed #68, Fixed #64

- README.md
- backup_generator.py
- bot/models/checked_claim.py
- requirements.txt
Fixed #66
I also fixed the backup generator so it works on Windows.
> Updated README.md to remove all technical information (which is organized better in the Wiki

- bot/bot.py
- bot/models/checked_claim.py
- bot/views/leaderboard_view.py
Fixed a bug with error messages when someone leaves the server. Also optimized the My Rank button by adding some SQL query parameters.
> Fixes and optimizing

- bot/views/leadstats_view.py
> Fixed dpi bug

- bot/forms/kudos_form.py
- bot/models/checked_claim.py
- bot/views/kudos_view.py
Now storing kudos comments in the Pings table
> Kudos comments

- bot/bot.py
- bot/models/checked_claim.py
- bot/views/claim_view.py
- bot/views/force_complete_view.py
- bot/views/force_unclaim_view.py
Deleted ephemeral messages by deferring the interaction and then deleting the original response.
Also added ForceUnclaimView which is shown when "Unclaim" is pressed by lead.
> Fixed #102

- bot/bot.py
- bot/cogs/leaderboard_command.py
- bot/helpers.py
- bot/views/leaderboard_view.py
Organized leaderboard, (hopefully) optimized it.
> 101 leaderboard code organization

- bot/bot.py
- bot/cogs/claim_command.py
- bot/cogs/leaderboard_command.py
- bot/forms/affirm_form.py
- bot/forms/ping_form.py
- bot/helpers.py
- bot/views/affirm_view.py
- bot/views/claim_view.py
- bot/views/resolve_ping_view.py
- requirements.txt
- sql/createdb.sql
This probably won't break anything.
> Edited messages, buttons, and delete_after times.

- bot/bot.py
- bot/cogs/award_command.py
- bot/helpers.py
- bot/models/team.py
- bot/models/team_point.py
- bot/views/leaderboard_view.py
- main.py
- sql/createdb.sql
DO NOT APPROVE/MERGE YET
```sql
SET FOREIGN_KEY_CHECKS=0;
#DROP TABLE TeamPoints;
CREATE TABLE `TeamPoints`(
`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`role_id` BIGINT UNSIGNED NOT NULL,
`points` TINYINT UNSIGNED NOT NULL,
`description` MEDIUMTEXT NOT NULL,
`timestamp` TIMESTAMP NOT NULL
);
ALTER TABLE Teams DROP COLUMN points;
```
> 111 enhance award

- bot/forms/edit_outage_form.py
- bot/forms/outage_form.py
Fixed a bug with outages where an error would occur when adding to the database. I added some input validation testing to ensure that an SQLError wouldn't be raised.
> 130 issue with removing outages

- bot/helpers/leaderboard_helpers.py
FIxed an issue where the leadstats graph would be unbalanced due to only checked cases being counted.
> Fixed issue

- bot/forms/ping_form.py
- bot/models/checked_claim.py
- bot/views/force_complete_view.py
Fixed obscure ping issue (the lead is reassigned in the table when /ping is used and a different lead is using it).
> 132 obscure ping issues

- bot/helpers/leaderboard_helpers.py
I added new leadstats labels that show how many total checked + pinged + kudos cases each lead has.
> 137 leadstats label

- bot/bot.py
- bot/cogs/heatmap_command.py
- requirements.txt
Adds the `/heatmap` command that creates a heatmap to show the correlations between leads and techs for case checking.
> 121 heatmap graph

- bot/cogs/caseinfo_command.py
> FEAT: Added a new feature for showing who is checking which cases'

- bot/cogs/caseinfo_command.py
Fixes an issue where CompletedClaims were queried for the /caseinfo and not all fields were populated. Added a check to prevent this from happening.
> Fix caseinfo

- bot/views/leaderboard_view.py
Added section in leaderboard_view.py to display the next rank user and the difference in cases.
> 162 my rank next place
